### ISSUE TITLE
Back button is the same as the browser back button

### ISSUE THREAD

**Issue by zsusag** [CSC322-Grinnell/boardbank#55]
Instead, the back button should go back in reference to the website, not in terms of where the browser has been. The back buttons should be hard-coded in some way using routes to prevent it being context specific.

**Comment by mashmouse** [comment]
WE WROTE A FAILING TEST IN CUCUMBER FOR THE BACK BUTTON IN THE USER SIGN IN PAGE!

**Comment by mashmouse** [comment]
We wrote tests for each page with a back button and then made the tests pass green
